language: java
os: linux
dist: focal
install: true
jdk:
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew codeCoverageReport
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
after_success:
  - bash <(curl -s https://codecov.io/bash)